# codedeploy
version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/ChaChatAPI
hooks:
  BeforeInstall:
    - location: ./codeclean.sh
      timeout: 180  
  AfterInstall:
    - location: ./codedeploy.sh
      timeout: 180  
